### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by scottnath**
@e2tha-e @rebmullin @sergesemashko @conortm @gvorbeck @beynya @nikkiana

This is a new version which incorporates the cloning function from plutilities
## In this pull request
- updating config.yml to include comments for what the variables are
- expanded README with "how to clone" and "how to import a pattern library"
- cloning task added to gulpfile
- minor updates to scss/js files

Once this is complete, I will publish the changes to NPM and the cloning feature will be available for you to use.

### CODE REVIEW

**Comment by e2tha-e** [comment]
@scottnath Doesn't work with the latest changes to pattern library utilities.

```
➜  generator-pattern-library-test git:(scottnath-minor-fixes) ✗ gulp build
module.js:338
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Hyunho/Sites/PatternLibrary/generator-pattern-library-test/node_modules/pattern-library-utilities/lib/gulp-tasks/clone.js:12:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by scottnath** [comment]
minimist wasn't in package.json for plutils. Please try again
@e2tha-e 
cc: @conortm

@rebmullin  @gvorbeck @nikkiana
You three are actively working on using this generator. Can you please check the README and let me know if those instructions are clear and if anything is missing?

**Comment by gvorbeck** [comment]
readme looks pretty good. :+1:

**Comment by e2tha-e** [comment]
@scottnath Works now. :+1: Merging

**Pull request merged**
