### PR TITLE
php errors when run by node

### PR DESCRIPTION
**Pull request by scottnath**
@e2tha-e @rebmullin @sergesemashko @conortm @beynya @nikkiana

This adds PHP error responses. Please review

relates to:
- https://github.com/pattern-library/generator-pattern-library/issues/6
- https://github.com/pattern-library/generator-pattern-library/issues/11

### CODE REVIEW

**Comment by sergesemashko** [comment]
:+1:

**Comment by scottnath** [comment]
@e2tha-e @rebmullin @sergesemashko @conortm @beynya @nikkiana

any other q's? ok to merge?

**Comment by e2tha-e** [comment]
@scottnath I didn't take a look but I think Serge's senior enough to have push access and merge PRs. Anywho if he gives the thumbs up, it's thumbs up for me as well.

**Comment by scottnath** [comment]
@e2tha-e @rebmullin @sergesemashko @conortm @beynya @nikkiana

agreed. don't we have a rule against merging your own PRs though?

**Comment by sergesemashko** [comment]
ok, merging then

**Pull request merged**
