### PR TITLE
remove pattern-importer/code cleanup

### LINKED ISSUE #7: creating pattern has undefined message
hey @scottnath  - when i create a pattern, it seems to work okay but i get the following message in terminal: http://grab.by/Khqg - see bottom messages

not sure really if this is an issue but didn't seem right...

### PR DESCRIPTION
**Pull request by scottnath**
Hey @e2tha-e 

This PR takes the changes from pattern-library-utilities and allows us to remove the `pattern-importer` repository all together. I also eslint-ed it and cleaned up the gulp file. Can you look this over please?

@rebmullin this also fixes [your bug](https://github.com/scottnath/generator-pattern-library/issues/7)

### CODE REVIEW

**Comment by scottnath** [comment]
@e2tha-e 

cc: @conortm @sergesemashko @beynya 

anyone have time to look at this pull request today? pretty basic changes.

**Comment by e2tha-e** [comment]
@scottnath I'll take a loook at it now

**Comment by e2tha-e** [comment]
@scottnath This pr looks good. Before I merge,  you might want to consider wrapping the entire js files in an IIFE and putting the `'use strict';` at the top of that, so linters don't complain and you don't have to repeat the `'use strict';` in each named function.

**Comment by scottnath** [comment]
hey @e2tha-e , node already does this. Adding an iife to node modules or a gulpfile is not necessary 

https://nodejs.org/api/modules.html#modules_modules
    Variables local to the module will be private, as though the module was wrapped in a function. In this example the variable PI is private to circle.js.

as for 'use strict' and the gulpfile, it really seems like the best practice is to have just a single 'use strict' at the top of gulpfile.js only. See this example from the tests for gulp:

https://github.com/gulpjs/gulp/blob/master/test/watch.js

I've never seen a gulpfile with 'use strict' anywhere but there....

**Comment by scottnath** [comment]
or from some of their recipes:

https://github.com/gulpjs/gulp/blob/506bac3f9f243cfda402b56143e2de2bae9418bc/docs/recipes/handling-the-delete-event-on-watch.md

**Comment by e2tha-e** [comment]
@scottnath Yes. I wasn't recommending this for any purpose other than to abide by linters that work across browser js and node js. If you're ok with leaving this pr as is, I'll merge it

**Comment by scottnath** [comment]
@e2tha-e totally ok with as is

(perhaps) unfortunately, node js and browser js are different beasts and will most likely require a different set of linting requirements.

**Comment by e2tha-e** [comment]
@scottnath If we decide to go that route, I have no objection, and would be willing to use commonly used and peer-reviewed node js standards for node files. Merging

**Comment by scottnath** [comment]
@e2tha-e thanks

**Pull request merged**
